# Generated by Django 4.2.13 on 2026-05-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=6)),
                ('pref_date', models.DateField()),
                ('request', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('booking_date', models.DateField()),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_mob_no', models.CharField(max_length=10)),
                ('c_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
