# Generated by Django 4.2.13 on 2026-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request',
        ),
        migrations.AddField(
            model_name='booking',
            name='requirements',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pin_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
